version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalog_mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - basket_redis_data:/data

  discountdb:
    container_name: discountdb
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin1234
    - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "6666:5432"
    volumes:
      - discount_postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
    - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8080:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__ConnectionString=basketdb:6379"
    depends_on:
      - basketdb
    ports:
      - "8081:80"

volumes:
  catalog_mongo_data:
  basket_redis_data:
  discount_postgres_data:
  pgadmin_data:
